version: '3.8'
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx-ce-dev
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    environment:
      - EMQX_NAME=emqx
      - EMQX_DASHBOARD__DEFAULT_USER__PASSWORD=public
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    restart: always

volumes:
  emqx-data:
  emqx-log:
  emqx-etc:
  mongodb-data:
