version: '3.8'
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx-ce-dev
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8883:8883"
      - "18083:18083"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - emqx-etc:/opt/emqx/etc
    environment:
      - EMQX_NAME=emqx
    restart: always
    networks:
      - autonomous

  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_APP_USERNAME=${MONGO_APP_USERNAME}
      - MONGO_APP_PASSWORD=${MONGO_APP_PASSWORD}
      - VEHICLE_ID=${VEHICLE_ID}
      - VEHICLE_NAME=${VEHICLE_NAME}
    restart: always
    networks:
      - autonomous

  telemetry_sender:
    build:
      context: ./integrations/send_telemetry
      dockerfile: Dockerfile
    container_name: telemetry_sender
    environment:
      - VEHICLE_ID=${VEHICLE_ID}
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - autonomous
    depends_on:
      - emqx


volumes:
  emqx-data:
  emqx-log:
  emqx-etc:
  mongodb-data:

networks:
  autonomous:
    driver: bridge
